const PDFDocument = require('pdfkit');

function safeFilePart(s) {
  const t = String(s || 'payroll')
    .replace(/[^\w.-]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
  return t.slice(0, 80) || 'payroll';
}

function formatMoney(value) {
  const num = Number(value || 0);
  return `GBP ${num.toFixed(2)}`;
}

function drawTableHeader(doc, startX, startY, colWidths, labels) {
  doc.font('Helvetica-Bold').fontSize(9).fillColor('#111111');
  let x = startX;
  for (let i = 0; i < labels.length; i += 1) {
    doc.rect(x, startY, colWidths[i], 24).fillAndStroke('#f3f4f6', '#d1d5db');
    doc.fillColor('#111111').text(labels[i], x + 6, startY + 8, {
      width: colWidths[i] - 12,
      align: i >= 2 ? 'right' : 'left',
    });
    x += colWidths[i];
  }
}

function drawRow(doc, startX, y, colWidths, row, isOdd) {
  const bg = isOdd ? '#ffffff' : '#fafafa';
  let x = startX;
  for (let i = 0; i < row.length; i += 1) {
    doc.rect(x, y, colWidths[i], 22).fillAndStroke(bg, '#e5e7eb');
    doc.fillColor('#111111').font('Helvetica').fontSize(9).text(String(row[i] ?? '-'), x + 6, y + 7, {
      width: colWidths[i] - 12,
      align: i >= 2 ? 'right' : 'left',
      ellipsis: true,
    });
    x += colWidths[i];
  }
}

function createPayrollPdf({ records, startDate, endDate, generatedBy }) {
  const doc = new PDFDocument({
    margin: 36,
    size: 'A4',
    layout: 'landscape',
  });

  const pageW = doc.page.width;
  const pageH = doc.page.height;
  const margin = 36;
  const tableStartX = margin;
  const colWidths = [170, 95, 70, 80, 80, 80, 95];
  const headers = ['Name', 'Role', 'Hrs', 'Sleep-in', 'Paid Hrs', 'Rate', 'Gross'];

  let y = margin;
  doc.font('Helvetica-Bold').fontSize(18).fillColor('#111111').text('Payroll Report', margin, y);
  y = doc.y + 6;

  doc.font('Helvetica').fontSize(10).fillColor('#374151');
  doc.text(`Period: ${startDate} to ${endDate}`, margin, y);
  y = doc.y + 2;
  doc.text(`Generated by: ${generatedBy || 'System'}`, margin, y);
  y = doc.y + 14;

  drawTableHeader(doc, tableStartX, y, colWidths, headers);
  y += 24;

  let totalRostered = 0;
  let totalSleepIn = 0;
  let totalPaid = 0;
  let totalGross = 0;

  records.forEach((record, idx) => {
    if (y + 22 > pageH - margin) {
      doc.addPage();
      y = margin;
      drawTableHeader(doc, tableStartX, y, colWidths, headers);
      y += 24;
    }

    totalRostered += Number(record.rostered_hours || 0);
    totalSleepIn += Number(record.sleep_in_hours || 0);
    totalPaid += Number(record.paid_hours || 0);
    totalGross += Number(record.gross_pay || 0);

    drawRow(doc, tableStartX, y, colWidths, [
      record.name || 'Unknown',
      record.role || '-',
      Number(record.rostered_hours || 0).toFixed(2),
      Number(record.sleep_in_hours || 0).toFixed(2),
      Number(record.paid_hours || 0).toFixed(2),
      formatMoney(record.hourly_rate || 0),
      formatMoney(record.gross_pay || 0),
    ], idx % 2 === 0);
    y += 22;
  });

  if (y + 80 > pageH - margin) {
    doc.addPage();
    y = margin;
  }

  doc.moveTo(margin, y + 8).lineTo(pageW - margin, y + 8).lineWidth(1).strokeColor('#d1d5db').stroke();
  y += 18;

  doc.font('Helvetica-Bold').fontSize(11).fillColor('#111111').text('Totals', margin, y);
  y = doc.y + 6;
  doc.font('Helvetica').fontSize(10);
  doc.text(`Total rostered hours: ${totalRostered.toFixed(2)}`, margin, y);
  doc.text(`Total sleep-in hours: ${totalSleepIn.toFixed(2)}`, margin, doc.y + 2);
  doc.text(`Total paid hours: ${totalPaid.toFixed(2)}`, margin, doc.y + 2);
  doc.text(`Total gross pay: ${formatMoney(totalGross)}`, margin, doc.y + 2);

  return doc;
}

module.exports = {
  createPayrollPdf,
  safeFilePart,
};
